name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci
      
- name: Radix ui
run: npm install @radix-ui/react-navigation-menu class-variance-authority

- name: Google Api's
run: npm install googleapis

    - name: Add navigation menu component
      run: npx shadcn-ui@latest add navigation-menu

    - name: Run linter
      run: npm run lint

    - name: Build
      run: npm run build

    - name: Run tests
      run: npm test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Deploy to production
      run: echo "Add your deployment steps here"
